### ISSUE TITLE
feature request

### ISSUE THREAD

**Issue by Lohita9** [ZiTanIOI/newBlackDex#3]
@ZiTanIOI Add a feature to easily distinguish dex files: name the unpacked app's dex files with a prefix cookies_[0-9].dex, and rename unrelated which is not dex files of unpacked app with a prefix hook_[0-9].dex.

**Comment by ZiTanIOI** [comment]
I will not add the feature rename dex file.Because it may cause many problem.

**Comment by Lohita9** [comment]
@ZiTanIOI It is difficult to distinguish the original Dex files of the corresponding app once it has been unpacked.
![Screenshot_2024-11-15-14-29-11-660_bin mt plus](https://github.com/user-attachments/assets/b67f98cc-8260-49d2-a9f8-05def7225d0e)

This app for testing: [Manual Camera_3.8_Encrypted.zip](https://github.com/user-attachments/files/17772347/Manual.Camera_3.8_Encrypted.zip)
This is original app without any encryption: [Manual Camera_3.8.zip](https://github.com/user-attachments/files/17772350/Manual.Camera_3.8.zip)

**Comment by Lohita9** [comment]
@ZiTanIOI Add a way to distinguish

**Comment by ZiTanIOI** [comment]
Blackdex use "cookie_" as the beginning of the dex file name to indicate that this dex file is located through mCookie and written from memory,use "hook_" as begin to indicate this dex is through hooking libart to get.The dex files obtained in these two ways are often duplicate, and only one needs to be kept(I recommend that you keep files with "cookie_" as the starting character of the file name, because cookie dump is more stable. That means you can delete all files whose names start with "hook_").All the extra dex files belong to blackdex itself, because blackdex counts its own dex in the running process. There is no good way to distinguish this. Fortunately, the dex file of blackdex will not change. When you dump for multiple different apps, what remains unchanged is the dex of blackdex.

**Comment by ZiTanIOI** [comment]
If you don't want to spend time distinguishing between them, You can also rename all the dex files directly to classes.dex, classes2.dex, classes3.dex. etc, Then add them all to the apk file The program can distinguish for itself which dex files it needs, and then load them.
